version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    working_dir: /app
    command: python app.py
